CREATE TABLE IF NOT EXISTS COUNTRY (
    COUNTRY_ID int(5) NOT NULL AUTO_INCREMENT,
    CODE varchar(2) NOT NULL DEFAULT '',
    NAME varchar(45) NOT NULL DEFAULT '',
    PRIMARY KEY (COUNTRY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;

CREATE TABLE IF NOT EXISTS STADIUM (
    STADIUM_ID int(5) NOT NULL AUTO_INCREMENT,
    COUNTRY_ID int(5) NOT NULL DEFAULT '191',
    NAME varchar(45) NOT NULL DEFAULT '',
    CITY varchar(45) NOT NULL DEFAULT '',
    PRIMARY KEY (STADIUM_ID),
    FOREIGN KEY (COUNTRY_ID)
        REFERENCES COUNTRY(COUNTRY_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;

CREATE TABLE IF NOT EXISTS CLUB (
    CLUB_ID INT(5) NOT NULL AUTO_INCREMENT,
    COUNTRY_ID INT(5) NOT NULL,
    NAME VARCHAR(45) DEFAULT '' NOT NULL,
    CITY VARCHAR(45) DEFAULT '' NOT NULL,
    SITE VARCHAR(45) DEFAULT '' NOT NULL,
    LOGO VARCHAR(45) DEFAULT '' NOT NULL,
    PRIMARY KEY (CLUB_ID),
    FOREIGN KEY (COUNTRY_ID)
        REFERENCES COUNTRY (COUNTRY_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;

CREATE TABLE IF NOT EXISTS POSITION (
    POSITION_ID INT(2) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(45) DEFAULT '' NOT NULL,
    PRIMARY KEY (POSITION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=0; 

CREATE TABLE IF NOT EXISTS PLAYER (
    PLAYER_ID INT(5) NOT NULL AUTO_INCREMENT,
    COUNTRY_ID INT(5) NOT NULL,
    NAME VARCHAR(45) DEFAULT '' NOT NULL,
    SQUAD_NUMBER INT(2) DEFAULT '0' NOT NULL,
    BIRTH_DATE DATE DEFAULT '1900-01-01' NOT NULL,
    POSITION_ID INT(2) NOT NULL DEFAULT '1',
    PRIMARY KEY (PLAYER_ID),
    FOREIGN KEY (COUNTRY_ID)
        REFERENCES COUNTRY (COUNTRY_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (POSITION_ID)
        REFERENCES POSITION (POSITION_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;


CREATE TABLE IF NOT EXISTS TRANSFER (
    TRANSFER_ID INT(5) NOT NULL AUTO_INCREMENT,
    CLUB_FROM INT(5) NOT NULL,
    CLUB_TO INT(5) NOT NULL,
    TRANSFER_DATE DATE DEFAULT '1900-01-01' NOT NULL,
    PRIMARY KEY (TRANSFER_ID),
    FOREIGN KEY (CLUB_FROM)
        REFERENCES CLUB (CLUB_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (CLUB_TO)
        REFERENCES CLUB (CLUB_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;

CREATE TABLE IF  NOT EXISTS PLAYER_TRANSFER (
    PLAYER_ID INT(5) NOT NULL,
    TRANSFER_ID INT(5) NOT NULL,
    PRIMARY KEY (PLAYER_ID, TRANSFER_ID),
    FOREIGN KEY (PLAYER_ID)
        REFERENCES PLAYER (PLAYER_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (TRANSFER_ID)
        REFERENCES TRANSFER (TRANSFER_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;

CREATE TABLE IF NOT EXISTS STADIUM_CLUB (
    STADIUM_ID int(5) NOT NULL,
    CLUB_ID int(5) NOT NULL,
    PRIMARY KEY (STADIUM_ID, CLUB_ID),
    FOREIGN KEY (STADIUM_ID) 
        REFERENCES STADIUM(STADIUM_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (CLUB_ID) 
        REFERENCES CLUB(CLUB_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;

CREATE TABLE IF NOT EXISTS CLUB_PLAYER (
    CLUB_ID int(5) NOT NULL,
    PLAYER_ID int(5) NOT NULL,
    PRIMARY KEY(CLUB_ID, PLAYER_ID),
    FOREIGN KEY (CLUB_ID)
        REFERENCES CLUB(CLUB_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (PLAYER_ID)
        REFERENCES PLAYER(PLAYER_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;

INSERT INTO `COUNTRY` VALUES (1, 'US', 'United States');
INSERT INTO `COUNTRY` VALUES (2, 'CA', 'Canada');
INSERT INTO `COUNTRY` VALUES (3, 'AF', 'Afghanistan');
INSERT INTO `COUNTRY` VALUES (4, 'AL', 'Albania');
INSERT INTO `COUNTRY` VALUES (5, 'DZ', 'Algeria');
INSERT INTO `COUNTRY` VALUES (6, 'DS', 'American Samoa');
INSERT INTO `COUNTRY` VALUES (7, 'AD', 'Andorra');
INSERT INTO `COUNTRY` VALUES (8, 'AO', 'Angola');
INSERT INTO `COUNTRY` VALUES (9, 'AI', 'Anguilla');
INSERT INTO `COUNTRY` VALUES (10, 'AQ', 'Antarctica');
INSERT INTO `COUNTRY` VALUES (11, 'AG', 'Antigua and/or Barbuda');
INSERT INTO `COUNTRY` VALUES (12, 'AR', 'Argentina');
INSERT INTO `COUNTRY` VALUES (13, 'AM', 'Armenia');
INSERT INTO `COUNTRY` VALUES (14, 'AW', 'Aruba');
INSERT INTO `COUNTRY` VALUES (15, 'AU', 'Australia');
INSERT INTO `COUNTRY` VALUES (16, 'AT', 'Austria');
INSERT INTO `COUNTRY` VALUES (17, 'AZ', 'Azerbaijan');
INSERT INTO `COUNTRY` VALUES (18, 'BS', 'Bahamas');
INSERT INTO `COUNTRY` VALUES (19, 'BH', 'Bahrain');
INSERT INTO `COUNTRY` VALUES (20, 'BD', 'Bangladesh');
INSERT INTO `COUNTRY` VALUES (21, 'BB', 'Barbados');
INSERT INTO `COUNTRY` VALUES (22, 'BY', 'Belarus');
INSERT INTO `COUNTRY` VALUES (23, 'BE', 'Belgium');
INSERT INTO `COUNTRY` VALUES (24, 'BZ', 'Belize');
INSERT INTO `COUNTRY` VALUES (25, 'BJ', 'Benin');
INSERT INTO `COUNTRY` VALUES (26, 'BM', 'Bermuda');
INSERT INTO `COUNTRY` VALUES (27, 'BT', 'Bhutan');
INSERT INTO `COUNTRY` VALUES (28, 'BO', 'Bolivia');
INSERT INTO `COUNTRY` VALUES (29, 'BA', 'Bosnia and Herzegovina');
INSERT INTO `COUNTRY` VALUES (30, 'BW', 'Botswana');
INSERT INTO `COUNTRY` VALUES (31, 'BV', 'Bouvet Island');
INSERT INTO `COUNTRY` VALUES (32, 'BR', 'Brazil');
INSERT INTO `COUNTRY` VALUES (33, 'IO', 'British lndian Ocean Territory');
INSERT INTO `COUNTRY` VALUES (34, 'BN', 'Brunei Darussalam');
INSERT INTO `COUNTRY` VALUES (35, 'BG', 'Bulgaria');
INSERT INTO `COUNTRY` VALUES (36, 'BF', 'Burkina Faso');
INSERT INTO `COUNTRY` VALUES (37, 'BI', 'Burundi');
INSERT INTO `COUNTRY` VALUES (38, 'KH', 'Cambodia');
INSERT INTO `COUNTRY` VALUES (39, 'CM', 'Cameroon');
INSERT INTO `COUNTRY` VALUES (40, 'CV', 'Cape Verde');
INSERT INTO `COUNTRY` VALUES (41, 'KY', 'Cayman Islands');
INSERT INTO `COUNTRY` VALUES (42, 'CF', 'Central African Republic');
INSERT INTO `COUNTRY` VALUES (43, 'TD', 'Chad');
INSERT INTO `COUNTRY` VALUES (44, 'CL', 'Chile');
INSERT INTO `COUNTRY` VALUES (45, 'CN', 'China');
INSERT INTO `COUNTRY` VALUES (46, 'CX', 'Christmas Island');
INSERT INTO `COUNTRY` VALUES (47, 'CC', 'Cocos (Keeling) Islands');
INSERT INTO `COUNTRY` VALUES (48, 'CO', 'Colombia');
INSERT INTO `COUNTRY` VALUES (49, 'KM', 'Comoros');
INSERT INTO `COUNTRY` VALUES (50, 'CG', 'Congo');
INSERT INTO `COUNTRY` VALUES (51, 'CK', 'Cook Islands');
INSERT INTO `COUNTRY` VALUES (52, 'CR', 'Costa Rica');
INSERT INTO `COUNTRY` VALUES (53, 'HR', 'Croatia (Hrvatska)');
INSERT INTO `COUNTRY` VALUES (54, 'CU', 'Cuba');
INSERT INTO `COUNTRY` VALUES (55, 'CY', 'Cyprus');
INSERT INTO `COUNTRY` VALUES (56, 'CZ', 'Czech Republic');
INSERT INTO `COUNTRY` VALUES (57, 'DK', 'Denmark');
INSERT INTO `COUNTRY` VALUES (58, 'DJ', 'Djibouti');
INSERT INTO `COUNTRY` VALUES (59, 'DM', 'Dominica');
INSERT INTO `COUNTRY` VALUES (60, 'DO', 'Dominican Republic');
INSERT INTO `COUNTRY` VALUES (61, 'TP', 'East Timor');
INSERT INTO `COUNTRY` VALUES (62, 'EC', 'Ecuador');
INSERT INTO `COUNTRY` VALUES (63, 'EG', 'Egypt');
INSERT INTO `COUNTRY` VALUES (64, 'SV', 'El Salvador');
INSERT INTO `COUNTRY` VALUES (65, 'GQ', 'Equatorial Guinea');
INSERT INTO `COUNTRY` VALUES (66, 'ER', 'Eritrea');
INSERT INTO `COUNTRY` VALUES (67, 'EE', 'Estonia');
INSERT INTO `COUNTRY` VALUES (68, 'ET', 'Ethiopia');
INSERT INTO `COUNTRY` VALUES (69, 'FK', 'Falkland Islands (Malvinas)');
INSERT INTO `COUNTRY` VALUES (70, 'FO', 'Faroe Islands');
INSERT INTO `COUNTRY` VALUES (71, 'FJ', 'Fiji');
INSERT INTO `COUNTRY` VALUES (72, 'FI', 'Finland');
INSERT INTO `COUNTRY` VALUES (73, 'FR', 'France');
INSERT INTO `COUNTRY` VALUES (74, 'FX', 'France, Metropolitan');
INSERT INTO `COUNTRY` VALUES (75, 'GF', 'French Guiana');
INSERT INTO `COUNTRY` VALUES (76, 'PF', 'French Polynesia');
INSERT INTO `COUNTRY` VALUES (77, 'TF', 'French Southern Territories');
INSERT INTO `COUNTRY` VALUES (78, 'GA', 'Gabon');
INSERT INTO `COUNTRY` VALUES (79, 'GM', 'Gambia');
INSERT INTO `COUNTRY` VALUES (80, 'GE', 'Georgia');
INSERT INTO `COUNTRY` VALUES (81, 'DE', 'Germany');
INSERT INTO `COUNTRY` VALUES (82, 'GH', 'Ghana');
INSERT INTO `COUNTRY` VALUES (83, 'GI', 'Gibraltar');
INSERT INTO `COUNTRY` VALUES (84, 'GR', 'Greece');
INSERT INTO `COUNTRY` VALUES (85, 'GL', 'Greenland');
INSERT INTO `COUNTRY` VALUES (86, 'GD', 'Grenada');
INSERT INTO `COUNTRY` VALUES (87, 'GP', 'Guadeloupe');
INSERT INTO `COUNTRY` VALUES (88, 'GU', 'Guam');
INSERT INTO `COUNTRY` VALUES (89, 'GT', 'Guatemala');
INSERT INTO `COUNTRY` VALUES (90, 'GN', 'Guinea');
INSERT INTO `COUNTRY` VALUES (91, 'GW', 'Guinea-Bissau');
INSERT INTO `COUNTRY` VALUES (92, 'GY', 'Guyana');
INSERT INTO `COUNTRY` VALUES (93, 'HT', 'Haiti');
INSERT INTO `COUNTRY` VALUES (94, 'HM', 'Heard and Mc Donald Islands');
INSERT INTO `COUNTRY` VALUES (95, 'HN', 'Honduras');
INSERT INTO `COUNTRY` VALUES (96, 'HK', 'Hong Kong');
INSERT INTO `COUNTRY` VALUES (97, 'HU', 'Hungary');
INSERT INTO `COUNTRY` VALUES (98, 'IS', 'Iceland');
INSERT INTO `COUNTRY` VALUES (99, 'IN', 'India');
INSERT INTO `COUNTRY` VALUES (100, 'ID', 'Indonesia');
INSERT INTO `COUNTRY` VALUES (101, 'IR', 'Iran (Islamic Republic of)');
INSERT INTO `COUNTRY` VALUES (102, 'IQ', 'Iraq');
INSERT INTO `COUNTRY` VALUES (103, 'IE', 'Ireland');
INSERT INTO `COUNTRY` VALUES (104, 'IL', 'Israel');
INSERT INTO `COUNTRY` VALUES (105, 'IT', 'Italy');
INSERT INTO `COUNTRY` VALUES (106, 'CI', 'Ivory Coast');
INSERT INTO `COUNTRY` VALUES (107, 'JM', 'Jamaica');
INSERT INTO `COUNTRY` VALUES (108, 'JP', 'Japan');
INSERT INTO `COUNTRY` VALUES (109, 'JO', 'Jordan');
INSERT INTO `COUNTRY` VALUES (110, 'KZ', 'Kazakhstan');
INSERT INTO `COUNTRY` VALUES (111, 'KE', 'Kenya');
INSERT INTO `COUNTRY` VALUES (112, 'KI', 'Kiribati');
INSERT INTO `COUNTRY` VALUES (113, 'KP', 'Korea, Democratic People''s Republic of');
INSERT INTO `COUNTRY` VALUES (114, 'KR', 'Korea, Republic of');
INSERT INTO `COUNTRY` VALUES (115, 'XK', 'Kosovo');
INSERT INTO `COUNTRY` VALUES (116, 'KW', 'Kuwait');
INSERT INTO `COUNTRY` VALUES (117, 'KG', 'Kyrgyzstan');
INSERT INTO `COUNTRY` VALUES (118, 'LA', 'Lao People''s Democratic Republic');
INSERT INTO `COUNTRY` VALUES (119, 'LV', 'Latvia');
INSERT INTO `COUNTRY` VALUES (120, 'LB', 'Lebanon');
INSERT INTO `COUNTRY` VALUES (121, 'LS', 'Lesotho');
INSERT INTO `COUNTRY` VALUES (122, 'LR', 'Liberia');
INSERT INTO `COUNTRY` VALUES (123, 'LY', 'Libyan Arab Jamahiriya');
INSERT INTO `COUNTRY` VALUES (124, 'LI', 'Liechtenstein');
INSERT INTO `COUNTRY` VALUES (125, 'LT', 'Lithuania');
INSERT INTO `COUNTRY` VALUES (126, 'LU', 'Luxembourg');
INSERT INTO `COUNTRY` VALUES (127, 'MO', 'Macau');
INSERT INTO `COUNTRY` VALUES (128, 'MK', 'Macedonia');
INSERT INTO `COUNTRY` VALUES (129, 'MG', 'Madagascar');
INSERT INTO `COUNTRY` VALUES (130, 'MW', 'Malawi');
INSERT INTO `COUNTRY` VALUES (131, 'MY', 'Malaysia');
INSERT INTO `COUNTRY` VALUES (132, 'MV', 'Maldives');
INSERT INTO `COUNTRY` VALUES (133, 'ML', 'Mali');
INSERT INTO `COUNTRY` VALUES (134, 'MT', 'Malta');
INSERT INTO `COUNTRY` VALUES (135, 'MH', 'Marshall Islands');
INSERT INTO `COUNTRY` VALUES (136, 'MQ', 'Martinique');
INSERT INTO `COUNTRY` VALUES (137, 'MR', 'Mauritania');
INSERT INTO `COUNTRY` VALUES (138, 'MU', 'Mauritius');
INSERT INTO `COUNTRY` VALUES (139, 'TY', 'Mayotte');
INSERT INTO `COUNTRY` VALUES (140, 'MX', 'Mexico');
INSERT INTO `COUNTRY` VALUES (141, 'FM', 'Micronesia, Federated States of');
INSERT INTO `COUNTRY` VALUES (142, 'MD', 'Moldova, Republic of');
INSERT INTO `COUNTRY` VALUES (143, 'MC', 'Monaco');
INSERT INTO `COUNTRY` VALUES (144, 'MN', 'Mongolia');
INSERT INTO `COUNTRY` VALUES (145, 'ME', 'Montenegro');
INSERT INTO `COUNTRY` VALUES (146, 'MS', 'Montserrat');
INSERT INTO `COUNTRY` VALUES (147, 'MA', 'Morocco');
INSERT INTO `COUNTRY` VALUES (148, 'MZ', 'Mozambique');
INSERT INTO `COUNTRY` VALUES (149, 'MM', 'Myanmar');
INSERT INTO `COUNTRY` VALUES (150, 'NA', 'Namibia');
INSERT INTO `COUNTRY` VALUES (151, 'NR', 'Nauru');
INSERT INTO `COUNTRY` VALUES (152, 'NP', 'Nepal');
INSERT INTO `COUNTRY` VALUES (153, 'NL', 'Netherlands');
INSERT INTO `COUNTRY` VALUES (154, 'AN', 'Netherlands Antilles');
INSERT INTO `COUNTRY` VALUES (155, 'NC', 'New Caledonia');
INSERT INTO `COUNTRY` VALUES (156, 'NZ', 'New Zealand');
INSERT INTO `COUNTRY` VALUES (157, 'NI', 'Nicaragua');
INSERT INTO `COUNTRY` VALUES (158, 'NE', 'Niger');
INSERT INTO `COUNTRY` VALUES (159, 'NG', 'Nigeria');
INSERT INTO `COUNTRY` VALUES (160, 'NU', 'Niue');
INSERT INTO `COUNTRY` VALUES (161, 'NF', 'Norfork Island');
INSERT INTO `COUNTRY` VALUES (162, 'MP', 'Northern Mariana Islands');
INSERT INTO `COUNTRY` VALUES (163, 'NO', 'Norway');
INSERT INTO `COUNTRY` VALUES (164, 'OM', 'Oman');
INSERT INTO `COUNTRY` VALUES (165, 'PK', 'Pakistan');
INSERT INTO `COUNTRY` VALUES (166, 'PW', 'Palau');
INSERT INTO `COUNTRY` VALUES (167, 'PA', 'Panama');
INSERT INTO `COUNTRY` VALUES (168, 'PG', 'Papua New Guinea');
INSERT INTO `COUNTRY` VALUES (169, 'PY', 'Paraguay');
INSERT INTO `COUNTRY` VALUES (170, 'PE', 'Peru');
INSERT INTO `COUNTRY` VALUES (171, 'PH', 'Philippines');
INSERT INTO `COUNTRY` VALUES (172, 'PN', 'Pitcairn');
INSERT INTO `COUNTRY` VALUES (173, 'PL', 'Poland');
INSERT INTO `COUNTRY` VALUES (174, 'PT', 'Portugal');
INSERT INTO `COUNTRY` VALUES (175, 'PR', 'Puerto Rico');
INSERT INTO `COUNTRY` VALUES (176, 'QA', 'Qatar');
INSERT INTO `COUNTRY` VALUES (177, 'RE', 'Reunion');
INSERT INTO `COUNTRY` VALUES (178, 'RO', 'Romania');
INSERT INTO `COUNTRY` VALUES (179, 'RU', 'Russian Federation');
INSERT INTO `COUNTRY` VALUES (180, 'RW', 'Rwanda');
INSERT INTO `COUNTRY` VALUES (181, 'KN', 'Saint Kitts and Nevis');
INSERT INTO `COUNTRY` VALUES (182, 'LC', 'Saint Lucia');
INSERT INTO `COUNTRY` VALUES (183, 'VC', 'Saint Vincent and the Grenadines');
INSERT INTO `COUNTRY` VALUES (184, 'WS', 'Samoa');
INSERT INTO `COUNTRY` VALUES (185, 'SM', 'San Marino');
INSERT INTO `COUNTRY` VALUES (186, 'ST', 'Sao Tome and Principe');
INSERT INTO `COUNTRY` VALUES (187, 'SA', 'Saudi Arabia');
INSERT INTO `COUNTRY` VALUES (188, 'SN', 'Senegal');
INSERT INTO `COUNTRY` VALUES (189, 'RS', 'Serbia');
INSERT INTO `COUNTRY` VALUES (190, 'SC', 'Seychelles');
INSERT INTO `COUNTRY` VALUES (191, 'SL', 'Sierra Leone');
INSERT INTO `COUNTRY` VALUES (192, 'SG', 'Singapore');
INSERT INTO `COUNTRY` VALUES (193, 'SK', 'Slovakia');
INSERT INTO `COUNTRY` VALUES (194, 'SI', 'Slovenia');
INSERT INTO `COUNTRY` VALUES (195, 'SB', 'Solomon Islands');
INSERT INTO `COUNTRY` VALUES (196, 'SO', 'Somalia');
INSERT INTO `COUNTRY` VALUES (197, 'ZA', 'South Africa');
INSERT INTO `COUNTRY` VALUES (198, 'GS', 'South Georgia South Sandwich Islands');
INSERT INTO `COUNTRY` VALUES (199, 'ES', 'Spain');
INSERT INTO `COUNTRY` VALUES (200, 'LK', 'Sri Lanka');
INSERT INTO `COUNTRY` VALUES (201, 'SH', 'St. Helena');
INSERT INTO `COUNTRY` VALUES (202, 'PM', 'St. Pierre and Miquelon');
INSERT INTO `COUNTRY` VALUES (203, 'SD', 'Sudan');
INSERT INTO `COUNTRY` VALUES (204, 'SR', 'Suriname');
INSERT INTO `COUNTRY` VALUES (205, 'SJ', 'Svalbarn and Jan Mayen Islands');
INSERT INTO `COUNTRY` VALUES (206, 'SZ', 'Swaziland');
INSERT INTO `COUNTRY` VALUES (207, 'SE', 'Sweden');
INSERT INTO `COUNTRY` VALUES (208, 'CH', 'Switzerland');
INSERT INTO `COUNTRY` VALUES (209, 'SY', 'Syrian Arab Republic');
INSERT INTO `COUNTRY` VALUES (210, 'TW', 'Taiwan');
INSERT INTO `COUNTRY` VALUES (211, 'TJ', 'Tajikistan');
INSERT INTO `COUNTRY` VALUES (212, 'TZ', 'Tanzania, United Republic of');
INSERT INTO `COUNTRY` VALUES (213, 'TH', 'Thailand');
INSERT INTO `COUNTRY` VALUES (214, 'TG', 'Togo');
INSERT INTO `COUNTRY` VALUES (215, 'TK', 'Tokelau');
INSERT INTO `COUNTRY` VALUES (216, 'TO', 'Tonga');
INSERT INTO `COUNTRY` VALUES (217, 'TT', 'Trinidad and Tobago');
INSERT INTO `COUNTRY` VALUES (218, 'TN', 'Tunisia');
INSERT INTO `COUNTRY` VALUES (219, 'TR', 'Turkey');
INSERT INTO `COUNTRY` VALUES (220, 'TM', 'Turkmenistan');
INSERT INTO `COUNTRY` VALUES (221, 'TC', 'Turks and Caicos Islands');
INSERT INTO `COUNTRY` VALUES (222, 'TV', 'Tuvalu');
INSERT INTO `COUNTRY` VALUES (223, 'UG', 'Uganda');
INSERT INTO `COUNTRY` VALUES (224, 'UA', 'Ukraine');
INSERT INTO `COUNTRY` VALUES (225, 'AE', 'United Arab Emirates');
INSERT INTO `COUNTRY` VALUES (226, 'GB', 'United Kingdom');
INSERT INTO `COUNTRY` VALUES (227, 'UM', 'United States minor outlying islands');
INSERT INTO `COUNTRY` VALUES (228, 'UY', 'Uruguay');
INSERT INTO `COUNTRY` VALUES (229, 'UZ', 'Uzbekistan');
INSERT INTO `COUNTRY` VALUES (230, 'VU', 'Vanuatu');
INSERT INTO `COUNTRY` VALUES (231, 'VA', 'Vatican City State');
INSERT INTO `COUNTRY` VALUES (232, 'VE', 'Venezuela');
INSERT INTO `COUNTRY` VALUES (233, 'VN', 'Vietnam');
INSERT INTO `COUNTRY` VALUES (234, 'VG', 'Virgin Islands (British)');
INSERT INTO `COUNTRY` VALUES (235, 'VI', 'Virgin Islands (U.S.)');
INSERT INTO `COUNTRY` VALUES (236, 'WF', 'Wallis and Futuna Islands');
INSERT INTO `COUNTRY` VALUES (237, 'EH', 'Western Sahara');
INSERT INTO `COUNTRY` VALUES (238, 'YE', 'Yemen');
INSERT INTO `COUNTRY` VALUES (239, 'YU', 'Yugoslavia');
INSERT INTO `COUNTRY` VALUES (240, 'ZR', 'Zaire');
INSERT INTO `COUNTRY` VALUES (241, 'ZM', 'Zambia');
INSERT INTO `COUNTRY` VALUES (242, 'ZW', 'Zimbabwe');